#:schema = "node_modules/wrangler/config-schema.json"
name = "noted"
main = "src/index.js"
compatibility_date = "2024-12-30"
compatibility_flags = [
	"nodejs_compat"
]

[build]
command = "npm install"

[env.development]
d1_databases = [
	{ binding = "DB", database_name = "noted", database_id = "cfcfa41e-7e7a-4d2b-912c-70a24251474b" }
]

r2_buckets = [
	{ binding = "R2_BUCKET", bucket_name = "noted-report-files" }
]

[env.production]
name = "noted"
d1_databases = [
	{ binding = "DB", database_name = "noted", database_id = "cfcfa41e-7e7a-4d2b-912c-70a24251474b" }
]
r2_buckets = [
	{ binding = "R2_BUCKET", bucket_name = "noted-report-files" }
]
